#!/usr/local/bin/python3
"""
DNS integration for Cloudflare Zero Trust.
Writes Unbound override configuration when gateway DNS or custom servers are configured.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from cfzt_config import get_config

UNBOUND_CONF_DIR = '/var/unbound/conf.d'
UNBOUND_CONF = f'{UNBOUND_CONF_DIR}/cloudflarezt.conf'
UNBOUND_CTL = '/usr/sbin/unbound-control'

# Cloudflare Gateway resolver (used when dns_mode=cloudflare_gateway)
GATEWAY_DNS_V4 = '162.159.36.1'
GATEWAY_DNS_V6 = '2606:4700:4700::1111'


def _build_unbound_conf(dns_cfg: dict) -> str:
    mode = dns_cfg.get('dns_mode', 'system')
    if mode == 'cloudflare_gateway':
        servers = [GATEWAY_DNS_V4, GATEWAY_DNS_V6]
    elif mode == 'custom':
        servers = [s.strip() for s in dns_cfg.get('custom_servers', '').split(',') if s.strip()]
    else:
        servers = []

    lines = ['# Generated by cloudflarezt — do not edit manually']
    if servers:
        lines += ['forward-zone:', '    name: "."']
        for addr in servers:
            addr = addr.replace('\n', '').replace('\r', '')
            lines.append(f'    forward-addr: {addr}')

    if dns_cfg.get('search_domains'):
        lines.append('server:')
        for domain in dns_cfg['search_domains'].split(','):
            domain = domain.strip().replace('\n', '').replace('\r', '')
            if domain:
                lines.append(f'    domain-insecure: "{domain}"')

    return '\n'.join(lines) + '\n'


def cmd_apply_dns() -> str:
    """Write Unbound config and reload if changed."""
    cfg = get_config()
    dns_cfg = cfg.get('dns', {})

    if not cfg['general']['enabled'] or dns_cfg.get('dns_mode', 'system') == 'system':
        _remove_conf()
        return 'dns override disabled'

    content = _build_unbound_conf(dns_cfg)
    os.makedirs(UNBOUND_CONF_DIR, mode=0o755, exist_ok=True)

    try:
        existing = open(UNBOUND_CONF).read()
    except FileNotFoundError:
        existing = None

    if content == existing:
        return 'no change'

    tmp = UNBOUND_CONF + '.tmp'
    with open(tmp, 'w') as f:
        f.write(content)
    os.replace(tmp, UNBOUND_CONF)

    _reload_unbound()
    return 'applied'


def cmd_remove_dns() -> str:
    _remove_conf()
    _reload_unbound()
    return 'removed'


def _remove_conf():
    try:
        os.unlink(UNBOUND_CONF)
    except FileNotFoundError:
        pass


def _reload_unbound():
    import subprocess
    try:
        subprocess.run([UNBOUND_CTL, 'reload'], capture_output=True, timeout=10)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass


if __name__ == '__main__':
    import json
    if len(sys.argv) < 2:
        print('Usage: dns.py <apply|remove>')
        sys.exit(1)
    cmd = sys.argv[1]
    if cmd == 'apply':
        print(cmd_apply_dns())
    elif cmd == 'remove':
        print(cmd_remove_dns())
    else:
        print(json.dumps({'result': 'failed', 'message': f'Unknown command: {cmd}'}))
        sys.exit(1)
